# Generated by Django 4.1.1 on 2022-10-22 18:14

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_username_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('postImage', models.ImageField(default=None, upload_to='postImages/')),
                ('timeCreated', models.DateTimeField(default=datetime.datetime(2022, 10, 22, 19, 14, 42, 424673))),
                ('noOfLikes', models.IntegerField(default=0)),
            ],
        ),
    ]
