# Generated by Django 4.1.1 on 2022-10-22 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 22, 19, 17, 17, 49886)),
        ),
    ]
