# Generated by Django 4.1.1 on 2022-10-22 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_posts_timecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(default=None, upload_to='postImages/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 22, 23, 19, 11, 668717)),
        ),
    ]
