# Generated by Django 4.1.1 on 2022-10-23 10:35

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_posts_postimage_alter_posts_timecreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('postImage', models.ImageField(default=None, upload_to='postImages/<django.db.models.fields.CharField>')),
                ('timeCreated', models.DateTimeField(default=datetime.datetime(2022, 10, 23, 11, 35, 42, 260873))),
                ('noOfLikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
