# Generated by Django 4.1.1 on 2022-10-25 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_likepost_alter_post_timecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='reaction_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 11, 37, 21, 542418)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 11, 37, 21, 542418)),
        ),
    ]
