# Generated by Django 4.1.1 on 2022-10-26 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_followers_alter_likepost_reaction_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
        migrations.AlterField(
            model_name='likepost',
            name='reaction_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 18, 21, 48, 841328)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 18, 21, 48, 840282)),
        ),
    ]
