# Generated by Django 4.1.1 on 2022-10-30 21:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_followers_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='reaction_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 22, 55, 2, 586800)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 22, 55, 2, 586800)),
        ),
    ]
