# Generated by Django 4.1.1 on 2022-11-01 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_post_name_alter_likepost_reaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='reaction_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 4, 24, 56, 333909)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 4, 24, 56, 332912)),
        ),
    ]
